### ISSUE TITLE
Content page error

### ISSUE THREAD

**Issue by ansonWuuuuu** [SAD-IM-project/lost_and_found#39]
<img width="743" alt="螢幕擷取畫面 2024-05-25 141812" src="https://github.com/SAD-IM-project/lost_and_found/assets/109121310/e4c8146c-ca38-48dc-8537-27e9fe89c300">
從 cody 那邊點進來以後會跳這個 error

**Comment by Hcy-43** [comment]
現在呢 我感覺修好了

**Comment by ansonWuuuuu** [comment]
好了好了
